plugins:
    ytdlp:
        updateOnStart: false # Whether to force update yt-dlp on startup
        binaryDirectory: "./bin" # Directory where yt-dlp binary is stored, defaults to OS specific temp dir (e.g. /tmp/ on Linux) + "/yt-dlp"

        # Path to cookies.txt file, may help with some age-restricted videos and rate limits
        # See https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp for more information
        cookiesFile: "./cookies.txt"

        searchLimit: 10 # Maximum number of search results to return
        playlistLimit: 16 # Maximum number of items to load from a playlist

        # Number of threads to use when loading a playlist (helps speed up loading as yt-dlp can be slow)
        # It's recommended that playlistLimit is set to a multiple of this value
        playlistThreads: 8

server: # REST and WS server
    port: 2333
    address: 0.0.0.0
    http2:
        enabled: false # Whether to enable HTTP/2 support

lavalink:
    plugins:
        - dependency: "com.github.gustavowidman:ytdlp-plugin:VERSION"
          repository: "https://jitpack.io"
    server:
        password: "youshallnotpass"
        sources:
            youtube: false # Disable default YouTube source since we're using yt-dlp
            bandcamp: true
            soundcloud: true
            twitch: true
            vimeo: true
            nico: true
            http: true # warning: keeping HTTP enabled without a proxy configured could expose your server's IP address.
            local: false
        filters: # All filters are enabled by default
            volume: true
            equalizer: true
            karaoke: true
            timescale: true
            tremolo: true
            vibrato: true
            distortion: true
            rotation: true
            channelMix: true
            lowPass: true
        nonAllocatingFrameBuffer: false # Setting to true reduces the number of allocations made by each player at the expense of frame rebuilding (e.g. non-instantaneous volume changes)
        bufferDurationMs: 400 # The duration of the NAS buffer. Higher values fare better against longer GC pauses. Duration <= 0 to disable JDA-NAS. Minimum of 40ms, lower values may introduce pauses.
        frameBufferDurationMs: 5000 # How many milliseconds of audio to keep buffered
        opusEncodingQuality: 10 # Opus encoder quality. Valid values range from 0 to 10, where 10 is best quality but is the most expensive on the CPU.
        resamplingQuality: LOW # Quality of resampling operations. Valid values are LOW, MEDIUM and HIGH, where HIGH uses the most CPU.
        trackStuckThresholdMs: 10000 # The threshold for how long a track can be stuck. A track is stuck if does not return any audio data.
        useSeekGhosting: true # Seek ghosting is the effect where whilst a seek is in progress, the audio buffer is read from until empty, or until seek is ready.
        youtubePlaylistLoadLimit: 6 # Number of pages at 100 each
        playerUpdateInterval: 5 # How frequently to send player updates to clients, in seconds
        youtubeSearchEnabled: false # Disable default YouTube search since we're using yt-dlp
        soundcloudSearchEnabled: true
        gc-warnings: true
#    ratelimit:
#      ipBlocks: [ "1.0.0.0/8", "..." ] # list of ip blocks
#      excludedIps: [ "...", "..." ] # ips which should be explicit excluded from usage by lavalink
#      strategy: "RotateOnBan" # RotateOnBan | LoadBalance | NanoSwitch | RotatingNanoSwitch
#      searchTriggersFail: true # Whether a search 429 should trigger marking the ip as failing
#      retryLimit: -1 # -1 = use default lavaplayer value | 0 = infinity | >0 = retry will happen this numbers times
#    youtubeConfig: # Required for avoiding all age restrictions by YouTube, some restricted videos still can be played without.
#      email: "" # Email of Google account
#      password: "" # Password of Google account
#    httpConfig: # Useful for blocking bad-actors from ip-grabbing your music node and attacking it, this way only the http proxy will be attacked
#      proxyHost: "localhost" # Hostname of the proxy, (ip or domain)
#      proxyPort: 3128 # Proxy port, 3128 is the default for squidProxy
#      proxyUser: "" # Optional user for basic authentication fields, leave blank if you don't use basic auth
#    proxyPassword: "" # Password for basic authentication

metrics:
    prometheus:
        enabled: false
        endpoint: /metrics

sentry:
    dsn: ""
    environment: ""
#  tags:
#    some_key: some_value
#    another_key: another_value

logging:
    file:
        path: ./logs/

    level:
        root: INFO
        lavalink: INFO

    request:
        enabled: true
        includeClientInfo: true
        includeHeaders: false
        includeQueryString: true
        includePayload: true
        maxPayloadLength: 10000

    logback:
        rollingpolicy:
            max-file-size: 1GB
            max-history: 30
